orgs:
  open-services-group:
    admins:
      - durandom
      - goern
      - tumido
      - Shreyanand
      - sesheta
    billing_email: goern@redhat.com
    company: "Red Hat, Inc."
    default_repository_permission: read
    description: The Open Services Group of Red Hatâ€˜s Emerging Technologies.
    email: ""
    has_organization_projects: true
    has_repository_projects: true
    location: Earth (any shape)
    members:
      - 4n4nd
      - aakankshaduggal
      - chauhankaranraj
      - codificat
      - erikerlandson
      - fridex
      - Gkrumbach07
      - Gregory-Pereira
      - harshad16
      - hemajv
      - HumairAK
      - KPostOffice
      - maroroman
      - mayaCostantini
      - MichaelClifford
      - mimotej
      - oindrillac
      - pacospace
      - SamoKopecky
      - schwesig
      - shreekarSS
      - suppathak
      - xtuchyna
      - dmick
    members_can_create_repositories: false
    name: Open Services Group
    repos:
      community:
        description:
          This repository handles a few common things, it is mainly used
          by our bots...
        has_projects: false
        has_wiki: false
      byon:
        description: Bring Your Own Notebook (BYON) project repository.
        has_projects: false
        has_wiki: false
      devsecops:
        description: ODH DevSecOps repository.
        has_projects: false
        has_wiki: false
      metrics:
        description: Metrics project repository.
        has_projects: false
        has_wiki: false
      peribolos-as-a-service:
        description: Declarative GitHub Organization management via Peribolos as a service
        has_projects: false
        has_wiki: false
    teams:
      AIOps:
        description: ""
        maintainers:
          - durandom
        members:
          - MichaelClifford
          - hemajv
          - tumido
          - Shreyanand
          - HumairAK
          - chauhankaranraj
          - 4n4nd
          - aakankshaduggal
        privacy: closed
        repos:
      DevOps:
        description: The DevOps Crew
        maintainers:
          - goern
          - harshad16
        members:
          - 4n4nd
        privacy: closed
        repos:
      SourceOps:
        description: This is our SourceOps team, they keep the source fresh.
        maintainers:
          - goern
          - harshad16
          - HumairAK
          - sesheta
          - tumido
        members:
        privacy: closed
        repos:
          byon: admin
          community: admin
          devsecops: admin
          metrics: admin
      Steering:
        description: The Open Services Group steering committee
        maintainers:
          - durandom
          - goern
          - schwesig
        members:
        privacy: closed
        repos:
          community: admin
      wg-byon-build-pipelines-leads:
        description: Leads Team for BYON project
        maintainers:
          - pacospace
          - oindrillac
        members:
        privacy: closed
        repos:
          byon: admin
      wg-devfail-leads:
        description: Leads Team for Device Failure Prediction WG
        maintainers:
          - dmick
          - erikerlandson
          - michaelclifford
        privacy: closed
      wg-devsecops-leads:
        description: Leads Team for DevSecOps
        maintainers:
          - HumairAK
          - harshad16
        members:
        privacy: closed
        repos:
          devsecops: admin
      sp-metrics-maintainers:
        description: Maintainers Team for the Metrics sub-project
        maintainers:
          - hemajv
          - Shreyanand
        members:
        privacy: closed
        repos:
          metrics: admin
      sp-peribolos-maintainers:
        description: Maintainers Team for the Peribolos-as-a-service sub-project
        maintainers:
          - tumido
          - Shreyanand
        privacy: closed
        repos:
          peribolos-as-a-service: admin
