orgs:
  open-services-group:
    admins:
      - durandom
      - goern
      - sesheta
    billing_email: goern@redhat.com
    company: "Red Hat, Inc."
    default_repository_permission: read
    description: The Open Services Group of Red Hatâ€˜s Emerging Technologies.
    email: ""
    has_organization_projects: true
    has_repository_projects: true
    location: Earth (any shape)
    members:
      - 4n4nd
      - aakankshaduggal
      - chauhankaranraj
      - codificat
      - erikerlandson
      - fridex
      - Gkrumbach07
      - harshad16
      - hemajv
      - HumairAK
      - KPostOffice
      - maroroman
      - mayaCostantini
      - MichaelClifford
      - mimotej
      - oindrillac
      - pacospace
      - schwesig
      - Shreyanand
      - suppathak
      - tumido
      - xtuchyna
    members_can_create_repositories: false
    name: Open Services Group
    repos:
      community:
        default_branch: main
        description:
          This repository handles a few common things, it is mainly used
          by our bots...
        has_projects: false
        has_wiki: false
      byon:
        default_branch: main
        description: Bring Your Own Notebook (BYON) project repository.
        has_projects: false
        has_wiki: false
      devsecops:
        default_branch: main
        description: ODH DevSecOps repository.
        has_projects: false
        has_wiki: false
    teams:
      AIOps:
        description: ""
        maintainers:
          - durandom
        members:
          - MichaelClifford
          - hemajv
          - tumido
          - Shreyanand
          - HumairAK
          - chauhankaranraj
          - 4n4nd
        privacy: closed
        repos:
      DevOps:
        description: The DevOps Crew
        maintainers:
          - goern
          - harshad16
        members:
          - 4n4nd
        privacy: closed
        repos:
      SourceOps:
        description: This is our SourceOps team, they keep the source fresh.
        maintainers:
          - goern
          - harshad16
          - sesheta
        members:
        privacy: closed
        repos:
          community: admin
      Steering:
        description: The Open Services Group steering committee
        maintainers:
          - durandom
          - goern
        members:
        privacy: closed
        repos:
          community: admin
          byon: admin
      wg-byon-build-pipelines-leads:
        description: Leads Team for BYON project
        maintainers:
          - pacospace
        members:
        privacy: closed
        repos:
          byon: admin
      wg-devsecops-leads:
        description: Leads Team for DevSecOps
        maintainers:
          - HumairAK
          - harshad16
        members:
        privacy: closed
        repos:
          devsecops: admin
